version: '3.3'

services:
  chrome_53:
    image: 'oldwebtoday/chrome:53'
    build:
      context: .
      args:
        BASE: 'oldwebtoday/base-browser:16.04'
        CHROME_DEB: google-chrome-stable_53.0.2785.143-1_amd64.deb

      labels:
        "wr.version": "53"
        "wr.release": "2016-09-24"
        "wr.caps.flash": "1"

  chrome_60:
    image: 'oldwebtoday/chrome:60'
    build:
      context: .
      args:
        CHROME_DEB: google-chrome-stable_60.0.3112.113-1_amd64.deb

      labels:
        "wr.version": "60"
        "wr.release": "2017-08-24"
        "wr.caps.flash": "1"

  chrome_67:
    image: 'oldwebtoday/chrome:67'
    build:
      context: .
      args:
        CHROME_DEB: google-chrome-stable_67.0.3396.99-1_amd64.deb

      labels:
        "wr.version": "67"
        "wr.release": "2018-05-29"
        "wr.caps.flash": "1"
        "wr.caps.autopilot": "1"

  chrome_73:
    image: 'oldwebtoday/chrome:73'
    build:
      context: .
      args:
        CHROME_DEB: google-chrome-stable_73.0.3683.75-1_amd64.deb

      labels:
        "wr.version": "73"
        "wr.release": "2019-03-12"
        "wr.caps.flash": "1"
        "wr.caps.autopilot": "1"

  chrome_76:
    image: 'oldwebtoday/chrome:76'
    build:
      context: .
      args:
        CHROME_DEB: google-chrome-stable_76.0.3809.100-1_amd64.deb

      labels:
        "wr.version": "76"
        "wr.release": "2019-08-05"
        "wr.caps.flash": "1"
        "wr.caps.autopilot": "1"

  chrome_84:
    image: 'oldwebtoday/chrome:84'
    build:
      context: .
      args:
        CHROME_DEB: google-chrome-stable_84.0.4147.89-1_amd64.deb

      labels:
        "wr.version": "84"
        "wr.release": "2020-07-14"
        "wr.caps.flash": "1"
        "wr.caps.autopilot": "1"

  chrome_88:
    image: 'oldwebtoday/chrome:88'
    build:
      context: .
      args:
        CHROME_DEB: google-chrome-stable_88.0.4324.96-1_amd64.deb

      labels:
        "wr.version": "88"
        "wr.release": "2021-01-19"
        "wr.caps.autopilot": "1"

  chrome_90:
    image: 'oldwebtoday/chrome:90'
    build:
      context: .
      args:
        CHROME_DEB: google-chrome-stable_90.0.4430.93-1_amd64.deb

      labels:
        "wr.version": "90"
        "wr.release": "2021-04-23"
        "wr.caps.autopilot": "1"

  chrome_91:
    image: 'oldwebtoday/chrome:91'
    build:
      context: .
      args:
        CHROME_DEB: google-chrome-stable_91.0.4472.101-1_amd64.deb

      labels:
        "wr.version": "90"
        "wr.release": "2021-06-08"
        "wr.caps.autopilot": "1"






